style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/aurorax-neo/free-gpt3.5-2api
options:
  commits:
    # filters:
    #   Type:
    #     - sparkles
    #     - bug
    #     - zap
    #     - recycle
  commit_groups:
    # title_maps:
    #   sparkles: Features
    #   bug: Bug Fixes
    #   zap: Performance Improvements
    #   recycle: Code Refactoring
  header:
    pattern: "^:(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE